export const assetPath = "/assets/arthritis";

export const img = {
  hero: `${assetPath}/hero.jpg`,
  stats: `${assetPath}/stats.jpg`,
  types: `${assetPath}/types.png`,
  osteo: `${assetPath}/osteo.jpg`,
  ra: `${assetPath}/ra.jpg`,
  gout: `${assetPath}/gout.jpg`,
  causes: `${assetPath}/causes.jpg`,
  solution: `${assetPath}/solution.jpg`,
  kitQr: `${assetPath}/kitQr.png`,
  orthoOilBanner: `${assetPath}/orthoOilBanner.jpg`,
  orthoOil1: `${assetPath}/orthoOil1.jpg`,
  orthoOil2: `${assetPath}/orthoOil2.jpg`,
  orthoOilHow: `${assetPath}/orthoOilHow.jpg`,
  orthoTabletBanner: `${assetPath}/orthoTabletBanner.jpg`,
  orthoTablet1: `${assetPath}/orthoTablet1.jpg`,
  orthoTablet2: `${assetPath}/orthoTablet2.jpg`,
  orthoTabletHow: `${assetPath}/orthoTabletHow.jpg`,
  boswelliaBanner: `${assetPath}/boswelliaBanner.jpg`,
  boswellia1: `${assetPath}/boswellia1.jpg`,
  boswellia2: `${assetPath}/boswellia2.jpg`,
  boswellia3: `${assetPath}/boswellia3.jpg`,
  boswelliaHow: `${assetPath}/boswelliaHow.jpg`,
  kaishorBanner: `${assetPath}/kaishorBanner.jpg`,
  kaishor1: `${assetPath}/kaishor1.jpg`,
  kaishor2: `${assetPath}/kaishor2.jpg`,
  kaishorHow: `${assetPath}/kaishorHow.jpg`,
  d3Banner: `${assetPath}/d3Banner.jpg`,
  d31: `${assetPath}/d31.jpg`,
  d32: `${assetPath}/d32.jpg`,
  d3How: `${assetPath}/d3How.jpg`,
  calciumBanner: `${assetPath}/calciumBanner.jpg`,
  calcium1: `${assetPath}/calcium1.jpg`,
  calcium2: `${assetPath}/calcium2.jpg`,
  calcium3: `${assetPath}/calcium3.jpg`,
  calciumHow: `${assetPath}/calciumHow.jpg`,
  footerGif: `${assetPath}/footerGif.gif`,
};

export const arthritisResults = {
  vid1: "/arthiritis results/WhatsApp Video 2026-04-15 at 1.50.55 PM.mp4",
  vid2: "/arthiritis results/WhatsApp Video 2026-04-15 at 12.27.08 PM.mp4",
  vid3: "/arthiritis results/WhatsApp Video 2026-04-15 at 12.28.48 PM.mp4",
};
